version: '3.9'

services:
  auth-server:
    build:
      context: .
      dockerfile: apps/auth-server/Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - vault
    networks:
      - app
      - monitoring

  main-server:
    build:
      context: .
      dockerfile: apps/main-server/Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - vault
      - auth-server
    networks:
      - app
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - '9200:9200'
    networks:
      - monitoring
      
  vault:
    image: hashicorp/vault
    ports:
      - '8200:8200'
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-token
    cap_add:
      - IPC_LOCK
    networks:
      - app
      - vault

  vault-init:
    build: ./infra/vault-init
    depends_on:
      - vault
    restart: 'no'
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-token
    networks:
      - vault

  waf:
    build:
      context: .
      dockerfile: infra/waf/Dockerfile
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - auth-server
      - main-server
    networks:
      - app

volumes:
  prometheus_data:
  grafana_data:

networks:
  app:
    driver: bridge
  monitoring:
    driver: bridge
  vault:
    driver: bridge
