global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'auth-server'
    static_configs:
      - targets: ['auth-server:4000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']